name: tintin
adopt-info: tintin
summary: TinTin++ is a scriptable MUD client.
description: TinTin++ is a MUD client that features an easy to learn yet powerful shell scripting language, a versatile automapper, and advanced VT100 interface controls.
icon: tintin-128.png

base: core24
grade: stable
confinement: strict

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64

apps:
  tintin:
    command: bin/tt++

parts:
  tintin:
    plugin: autotools
    source: https://github.com/scandum/tintin
    source-type: git
    source-branch: master
    source-subdir: src
    build-packages:
      - gcc
      - make
      - libpcre2-dev
      - zlib1g-dev
      - gnutls-dev
    override-build: |
      ./configure
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp tt++ $SNAPCRAFT_PART_INSTALL/bin/

      VERSION=$(head -n 1 ../mods/igr.mods | awk '{print $3}' | tr -d '\r')
      craftctl set version="$VERSION"
